WIP - Added unit tests
ceph/ceph-mixins pull request #56
Opened 2019-05-13 11:20 UTC by shtripat

ceph-mixins-bug-id: ceph/ceph-mixins/issues/55
Signed-off-by: Shubhendu <shtripat@redhat.com>

2019-05-13 16:42 UTC, shtripat commented
@umangachapagain @cloudbehl @anmolsachan please review.

2019-05-15 09:47 UTC, umangachapagain requested changes
Remove changes in `alerts/node.libsonnet` & `rules/rules.libsonnet`.

2019-05-15 09:53 UTC, shtripat commented
> Remove changes in `alerts/node.libsonnet` & `rules/rules.libsonnet`.

@umangachapagain these changes I needed to write test cases under `test_rules.yaml` for recording rules. In actual alerting rules I have added the check equality for 0/1

2019-05-16 13:39 UTC, umangachapagain approved these changes

2019-05-16 13:40 UTC, merged